### ISSUE TITLE
Moonstone ore being placed on non-biome blocks

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#13]
Last I checked, Moonstone meteor strikes were only supposed to occur on  biome surface blocks.

I just now had moonstone be placed over/under my crafting altar.

![2016-10-13_00 02 48](https://cloud.githubusercontent.com/assets/1569754/19339544/db26ba60-90d8-11e6-8f28-5efd0597d5f3.png)

Also they seem larger and more destructive than I remember? I'm having to fill in some pretty large potholes, typically at least 4 blocks.

**Comment by EdwinMindcraft** [comment]
Moonstone can only fall on the top block but can theoretically spawn anywhere in a 4x4 zone inside it... And for the destruction... Well I didn't  change anything...

**Comment by esotericist** [comment]
Whoops, meant to comment on this the other day.

Weird that you didn't change anything, I remember moonstone being 1-3 ore blocks and maybe a block or two of destroyed terrain.

I mean, I guess it isn't a problem, it just caught me off guard. Probably call it not a bug?

**Comment by EdwinMindcraft** [comment]
In 1.9.4 it's 8 block max if it drops in the corner of 4 blocks... And I did make meteors generate more ore. But since I changed it to be spawning in a more frequent state I'm just going to revert it.

If you want to try and spawn one in creative use this:
`/summon arsmagica2.ThrownRock ~ ~ ~ {MoonstoneMeteor:1b}`
