### ISSUE TITLE
ArsMagica 2.0.4 really heavy framedrops

### ISSUE THREAD

**Issue by Gamewalker** [EdwinMindcraft/ArsMagica2#6]
Hello,

if we place "Essence Refiner", "Inscription Table" or "Lectern", we lose 1/3-2/3 of our Frames. Can u look into it? If u need anymore information just tell me :)

Greetings

ps: if u need anything specific tested, we are 5 people willing to test the AM2 things on our server.

**Comment by EdwinMindcraft** [comment]
I'll take a look. But this doesn't make any sense...

**Comment by EdwinMindcraft** [comment]
Can you test out any other power-related machine? Crafting Altar, Obelisk?

**Comment by EdwinMindcraft** [comment]
And to answer the ps : I'd be glad if you could but I didn't test more than server-side launching and not crashing with a few blocks...

**Comment by Gamewalker** [comment]
The FPS drop for Crafting Altar is even worse and if I place the blocks, they sometimes dont show and the FPS wont drop. I was lucky and got the things on video:
http://plays.tv/video/57fa76cf5b44368b7f/ars-magica-2-0-4-bugtesting-for-1-10-2

**Comment by esotericist** [comment]
Doing some performance testing of various things, and it may or may not be useful for you to know that I don't see any measurable performance hit looking at the occulus, inscription table, or crafting altar _unless_ I have smooth lighting enabled. 

(Which I don't, normally, because the stepped lighting helps me judge distances)

**Comment by EdwinMindcraft** [comment]
Owww then that's not my fault... That minecraft engine that does it...

**Comment by esotericist** [comment]
Probably not. The smooth lighting renderer has a lot of jankiness, especially when mods hook into it; for example I have ArchitectureCraft installed on the instance I'm doing my testing on right now, it may or may not play a role since it has to tamper with the smooth lighting routines for its non-cubic blocks to work right.

Unfortunately I just cannot measure a performance hit when I run AM2 by itself. It just doesn't stress my computer hard enough, and I don't have any of the fancy instrumentation tools to do fine-grained measurements. :(

**Comment by EdwinMindcraft** [comment]
I'll probably end un forcing flat lighting rendering.

**Comment by esotericist** [comment]
Can you do that on blocks/TEs selectively?

**Comment by EdwinMindcraft** [comment]
Well there's a drawModelFlat method that is called if smooth lighting is off so... It will be a bit of Reflection if the method isn't available.

**Comment by esotericist** [comment]
Good to know. I wasn't able to load the video @Gamewalker posted, was smooth lighting enabled there? If so, might be a useful step to perform over there to find out if that's their problem?

**Comment by Gamewalker** [comment]
I will test it when I am home, I dont know if its enabled or disabled

Am 12.10.2016 13:02 schrieb "eso" notifications@github.com:

**Comment by Gamewalker** [comment]
No difference between SM on and off. I dont have a problem with the performance but my friends dont have the newest shit and if they enter my area, they play with 10 fps until I break the AM blocks ^^

**Comment by EdwinMindcraft** [comment]
try updating... I don't know if I did great or not in the last release.

**Comment by esotericist** [comment]
So, news!

Sadly, it is not good news.

I've been cranking up the number of things I have going on in my survival world, including a lot of different aesthetic mods, and various things that might impact performance.

Well, at some point, I managed to reproduce the issue @Gamewalker was having. With any of various AM2 blocks in view, framerate plummets pretty hard. 

I recorded a video to demonstrate.

https://youtu.be/WcuOMUiHs-o

I don't know yet if it's some combination of mods causing the issue, or if it's simply only visible now because my system is sufficiently by everything else going on, but it's pretty stark; you can watch my framerate go from around 38-45 FPS to 20 FPS just by placing either the lectern or the import crystal.

I'll do some more investigating on my end, but I thought I should let you know.

**Comment by esotericist** [comment]
Okay, I can currently replicate it with just AM2 alone, in a normal world with a 32 chunk render distance. Dropping from ~ 60 fps to ~ 40 fps by placing an import crystal on the ground.

I'd _been_ doing a bunch of my testing in a void world, and it only today occurred to me that might make it hard to measure graphics performance problems.  The original purpose was to minimize tick load stuff and to make things load fast, but well.

Edit: AM2 2.0.8, forge 2094 still.

**Comment by esotericist** [comment]
I can now confirm in the exact same test world, in the exact same circumstances, AM2 2.0.7 does NOT exhibit the frame loss. So something changed between 2.0.7 and 2.0.8 for rendering for me.

**Comment by esotericist** [comment]
... Disregard above. It is just more inconsistent. Which is just weird. 

I don't know. I should probably leave this alone for a while, since I obviously have no idea what I'm doing.

**Comment by esotericist** [comment]
The most interesting thing to me about the framerate issue is that it doesn't appear to be cumulative. one AM2 TE, two AM2 TEs, twenty, the impact seems to be the same. So whatever the problem is, it isn't a per-tile entity issue.

**Comment by EdwinMindcraft** [comment]
Probably the power system then...

**Comment by esotericist** [comment]
Seems to be the case. Notable item:

https://github.com/EdwinMindcraft/ArsMagica2/blob/1.9-Rework/src/main/java/am2/blocks/tileentity/TileEntityAMPower.java#L57

It seems to unconditionally generate updates that sync to the client, regardless of whether or not request interval has occurred.

Pushing that line up one (disclaimer: still not a java programmer) to put it inside that conditional has fairly dramatic effects on some (but not all) tile entities.

For instance, it allows me to place armor imbuement table, flicker habitat, occulus, and even the obelisk without observable framerate problems.

Inscription table, import crystal, lectern, and crafting altar still exhibit the problem. 

Hopefully this information is helpful.

**Comment by esotericist** [comment]
To further add: with the current tree -- minus my blind-flailing edit -- any of the above mentioned tile entities causes a storm of constant chunk updates. 

With my blind-flailing edit, the tile entities that stop exhibiting framerate problems are no longer generating constant chunk updates.
